In [1]:
import numpy as np
import pandas as pd

In [2]:
file_name='7.temperature_data_1980_2021.xls'
df=pd.read_excel(file_name)

In [3]:
df

年份  Temp（C）  降水量(mm)  降水天数  平均海平面气压(hPa)  平均风速(knots)    NDVI  \
0   2000    -0.90   524.00   143       1014.50         3.92  0.4716   
1   2001    -0.02   419.61   151       1013.89         3.42  0.4897   
2   2002     0.87   421.39   119       1014.39         3.54  0.5303   
3   2003    -0.05   606.55   108       1015.44         3.29  0.4883   
4   2004     0.28   543.81   119       1013.96         3.19  0.4682   
5   2005     0.74   328.68    95       1013.71         3.34  0.4840   
6   2006    -0.91   418.85   101       1014.36         3.24  0.5022   
7   2007     0.89   329.95    89       1013.93         3.25  0.5275   
8   2008     1.33   451.36   108       1013.47         3.33  0.5231   
9   2009    -0.60   627.38   150       1013.77         3.54  0.5116   
10  2010     0.06   545.85   115       1013.85         3.19  0.4945   
11  2011     0.86   443.74    95       1014.20         2.99  0.5355   
12  2012    -0.61   491.49   114       1014.17         2.73  0.5286   
13  2013    -1.07   677.67   120       1012.65         5.92  0.5423   
14  2014    -0.65   388.87    88       1014.87         5.98  0.5772   
15  2015     0.08   467.36    97       1014.83         5.72  0.5702   
16  2016    -1.55   467.36   116       1014.15         5.91  0.5588   
17  2017    -0.08   522.73   110       1012.75         6.33  0.6001   
18  2018    -0.42   478.79    96       1013.56         6.02  0.5953   
19  2019    -0.73   503.68   120       1013.16         5.93  0.6297   
20  2020     0.07   763.52    98       1014.08         5.65  0.6168   
21  2021    -0.16   639.06   107       1013.58         5.77  0.6142   

    CO2排放量(μg/m2)  CO2吸收量(μg/m2)  
0      2716535.61            NaN  
1      2835461.26            NaN  
2      2923113.13            NaN  
3      3016845.11            NaN  
4      3156113.56            NaN  
5      3454698.62            NaN  
6     37165151.20            NaN  
7      3978312.87            NaN  
8      4658753.11            NaN  
9      4245686.74            NaN  
10     4612568.62            NaN  
11     4834613.32            NaN  
12     5116895.10            NaN  
13     5345941.68            NaN  
14     5756131.89            NaN  
15     6246586.14            NaN  
16     6854563.72            NaN  
17     7356498.61            NaN  
18     7669876.56            NaN  
19     8164235.27            NaN  
20     8715613.96            NaN  
21     9599027.03            NaN

In [4]:
co2_release=df['CO2排放量(μg/m2)']
co2_absorb=df['CO2吸收量(μg/m2)']
demo=np.array(co2_release)
demo=[x for x in demo+np.random.rand(1,22)*1000000]
demo=np.array(demo)
demo

array([[ 3259034.62154069,  3211582.06141794,  2927543.49478231,
         3019086.14352174,  3183435.38816846,  3687531.21433235,
        37439426.51893071,  4564347.11681067,  5493569.08001053,
         4912283.32775244,  4969034.75445028,  5160255.05068576,
         5269198.40723506,  6013455.64283218,  6001980.71839752,
         7034213.35342468,  7613695.97549854,  7464368.86194486,
         7676478.20556446,  8849119.05176282,  8908794.51595492,
         9614785.25244921]])

In [5]:
df['CO2吸收量(μg/m2)']=pd.DataFrame(demo+np.random.rand(1,22)*100)

In [6]:
df

年份  Temp（C）  降水量(mm)  降水天数  平均海平面气压(hPa)  平均风速(knots)    NDVI  \
0   2000    -0.90   524.00   143       1014.50         3.92  0.4716   
1   2001    -0.02   419.61   151       1013.89         3.42  0.4897   
2   2002     0.87   421.39   119       1014.39         3.54  0.5303   
3   2003    -0.05   606.55   108       1015.44         3.29  0.4883   
4   2004     0.28   543.81   119       1013.96         3.19  0.4682   
5   2005     0.74   328.68    95       1013.71         3.34  0.4840   
6   2006    -0.91   418.85   101       1014.36         3.24  0.5022   
7   2007     0.89   329.95    89       1013.93         3.25  0.5275   
8   2008     1.33   451.36   108       1013.47         3.33  0.5231   
9   2009    -0.60   627.38   150       1013.77         3.54  0.5116   
10  2010     0.06   545.85   115       1013.85         3.19  0.4945   
11  2011     0.86   443.74    95       1014.20         2.99  0.5355   
12  2012    -0.61   491.49   114       1014.17         2.73  0.5286   
13  2013    -1.07   677.67   120       1012.65         5.92  0.5423   
14  2014    -0.65   388.87    88       1014.87         5.98  0.5772   
15  2015     0.08   467.36    97       1014.83         5.72  0.5702   
16  2016    -1.55   467.36   116       1014.15         5.91  0.5588   
17  2017    -0.08   522.73   110       1012.75         6.33  0.6001   
18  2018    -0.42   478.79    96       1013.56         6.02  0.5953   
19  2019    -0.73   503.68   120       1013.16         5.93  0.6297   
20  2020     0.07   763.52    98       1014.08         5.65  0.6168   
21  2021    -0.16   639.06   107       1013.58         5.77  0.6142   

    CO2排放量(μg/m2)  CO2吸收量(μg/m2)  
0      2716535.61   3.259039e+06  
1      2835461.26            NaN  
2      2923113.13            NaN  
3      3016845.11            NaN  
4      3156113.56            NaN  
5      3454698.62            NaN  
6     37165151.20            NaN  
7      3978312.87            NaN  
8      4658753.11            NaN  
9      4245686.74            NaN  
10     4612568.62            NaN  
11     4834613.32            NaN  
12     5116895.10            NaN  
13     5345941.68            NaN  
14     5756131.89            NaN  
15     6246586.14            NaN  
16     6854563.72            NaN  
17     7356498.61            NaN  
18     7669876.56            NaN  
19     8164235.27            NaN  
20     8715613.96            NaN  
21     9599027.03            NaN

In [7]:

import numpy as np
import pandas as pd
import torch
from torch import nn
from d2l import torch as d2l

file_name2='params by times_2000-2021_v2_normalized.xlsx'
data=pd.read_excel(file_name2)
train_data=data.loc[::2]
test_data=data.loc[1::2]
print(test_data.shape)

D:\Anacoda\lib\site-packages\torchvision\io\image.py:11: UserWarning: Failed to load image Python extension: Could not find module 'D:\Anacoda\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")


(11, 7)


In [8]:
train_data

Years  Ave_temperature  Rain_storage  Rain_total_day  CO2_release    NDVI  \
0    2000            -0.90        524.00             143   2716535.61  0.4716   
2    2002             0.87        421.39             119   2923113.13  0.5303   
4    2004             0.28        543.81             119   3156113.56  0.4682   
6    2006            -0.91        418.85             101   3716551.21  0.5022   
8    2008             1.33        451.36             108   4658753.11  0.5231   
10   2010             0.06        545.85             115   4612568.62  0.4945   
12   2012            -0.61        491.49             114   5116895.19  0.5286   
14   2014            -0.65        388.87              88   5756131.89  0.5772   
16   2016            -1.55        467.36             116   6854563.72  0.5588   
18   2018            -0.42        478.79              96   7669876.56  0.5953   
20   2020             0.07        763.52              98   8715613.96  0.6168   

     CO2_absorb  
0   7760187.535  
2   7681651.456  
4   7621300.561  
6   4041614.271  
8   7357867.015  
10  7894283.392  
12  7368116.561  
14  7345643.135  
16  7299489.461  
18  7056498.156  
20  6998431.455

In [9]:
#将所有缺失的值替换为相应特征的平均值。 通过将特征重新缩放到零均值和单位方差来标准化数据
numeric_features =data.dtypes[data.dtypes != 'object'].index
data[numeric_features] = data[numeric_features].apply(lambda x: (x - x.mean()) / (x.std()))
data[numeric_features] = data[numeric_features].fillna(0)
# 处理离散值
data = pd.get_dummies(data, dummy_na=True) # one-hot 处理
data

Years  Ave_temperature  Rain_storage  Rain_total_day  CO2_release  \
0  -1.616980        -1.059143      0.193907        1.745416    -1.214190   
1  -1.462982         0.130933     -0.761108        2.192567    -1.156651   
2  -1.308984         1.334532     -0.744823        0.403961    -1.114243   
3  -1.154986         0.090362      0.949118       -0.210873    -1.068894   
4  -1.000988         0.536640      0.375140        0.403961    -1.001513   
5  -0.846990         1.158725     -1.592984       -0.937494    -0.857051   
6  -0.692991        -1.072666     -0.768061       -0.602130    -0.730361   
7  -0.538993         1.361579     -1.581365       -1.272858    -0.603715   
8  -0.384995         1.956617     -0.470642       -0.210873    -0.274504   
9  -0.230997        -0.653435      1.139682        2.136673    -0.474354   
10 -0.076999         0.239122      0.393803        0.180385    -0.296849   
11  0.076999         1.321008     -0.540354       -0.937494    -0.189419   
12  0.230997        -0.666959     -0.103511        0.124491    -0.052845   
13  0.384995        -1.289044      1.599762        0.459855     0.057973   
14  0.538993        -0.721053     -1.042334       -1.328752     0.256431   
15  0.692991         0.266169     -0.324265       -0.825706     0.493723   
16  0.846990        -1.938176     -0.324265        0.236279     0.787876   
17  1.000988         0.049791      0.182289       -0.099085     1.030723   
18  1.154986        -0.410011     -0.219698       -0.881600     1.182342   
19  1.308984        -0.829242      0.008009        0.459855     1.421523   
20  1.462982         0.252645      2.385163       -0.769812     1.688291   
21  1.616980        -0.058397      1.246537       -0.266767     2.115705   

        NDVI  CO2_absorb  
0  -1.357055    0.625417  
1  -0.993041    0.442714  
2  -0.176522    0.526156  
3  -1.021197    0.866981  
4  -1.425434    0.449879  
5  -1.107675   -0.315655  
6  -0.741650   -4.074448  
7  -0.232834    0.684571  
8  -0.321324    0.116928  
9  -0.552604    0.549170  
10 -0.896507    0.794899  
11 -0.071944    0.463382  
12 -0.210712    0.129883  
13  0.064813    0.247986  
14  0.766697    0.101479  
15  0.625918   -0.163932  
16  0.396650    0.043146  
17  1.227246    0.113238  
18  1.130712   -0.263969  
19  1.822540   -0.365060  
20  1.563105   -0.337358  
21  1.510815   -0.635406

In [10]:
numeric_features

Index(['Years', 'Ave_temperature', 'Rain_storage', 'Rain_total_day',
       'CO2_release', 'NDVI', 'CO2_absorb'],
      dtype='object')

In [11]:
# 特征提取
n_train = train_data.shape[0]
# 划分
train_features = torch.tensor(data[:n_train].values,dtype=torch.float32)
test_features = torch.tensor(data[n_train:].values,
                             dtype=torch.float32)
train_labels = torch.tensor(train_data['CO2_absorb'].values,
                            dtype=torch.float32)
test_labels = torch.tensor(train_data['CO2_absorb'].values,
                            dtype=torch.float32)


In [12]:
# Train
loss = nn.MSELoss()
in_features = train_features.shape[1] # 特征个数
net = nn.Sequential(nn.Linear(in_features, 1)) # 定义网络
def get_net():
    net = nn.Sequential(nn.Linear(in_features, 1))
    return net

def log_rmse(net, features, labels):
    clipped_preds = torch.clamp(net(features), 1, float('inf'))
    rmse = torch.sqrt(loss(torch.log(clipped_preds), torch.log(labels)))
    return rmse.item()

def train(net, train_features, train_labels, test_features, test_labels,
          num_epochs, learning_rate, weight_decay, batch_size):
    train_ls, test_ls = [], []
    train_iter = d2l.load_array((train_features, train_labels), batch_size)
    optimizer = torch.optim.Adam(net.parameters(), lr=learning_rate,weight_decay=weight_decay)
    for epoch in range(num_epochs):
        for X, y in train_iter:
            optimizer.zero_grad()
            l = loss(net(X), y)
            l.backward()
            optimizer.step()
        train_ls.append(log_rmse(net, train_features, train_labels))
        if test_labels is not None:
            test_ls.append(log_rmse(net, test_features, test_labels))
    return train_ls, test_ls
train(net, train_features, train_labels, test_features, test_labels,
          10, 0.1, 0, 3)

D:\Anacoda\lib\site-packages\torch\nn\modules\loss.py:520: UserWarning: Using a target size (torch.Size([3])) that is different to the input size (torch.Size([3, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
D:\Anacoda\lib\site-packages\torch\nn\modules\loss.py:520: UserWarning: Using a target size (torch.Size([2])) that is different to the input size (torch.Size([2, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
D:\Anacoda\lib\site-packages\torch\nn\modules\loss.py:520: UserWarning: Using a target size (torch.Size([11])) that is different to the input size (torch.Size([11, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
 [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [19]:
# k-fold cross 
def get_k_fold_data(k, i, X, y):
    assert k > 1
    fold_size = X.shape[0] // k
    X_train, y_train = None, None
    for j in range(k):
        # slice方法可从已有数组中返回选定的元素，返回一个新数组，包含从start到end（不包含该元素）的数组元素。
        idx = slice(j * fold_size, (j + 1) * fold_size)
        #print(idx)
        X_part, y_part = X[idx, :], y[idx]
        if j == i:
            X_valid, y_valid = X_part, y_part
        elif X_train is None:
            X_train, y_train = X_part, y_part
        else:
            X_train = torch.cat([X_train, X_part], 0)
            y_train = torch.cat([y_train, y_part], 0)
    return X_train, y_train, X_valid, y_valid

def k_fold(k, X_train, y_train, num_epochs, learning_rate, weight_decay,
           batch_size):
    
    train_l_sum, valid_l_sum = 0, 0
    arr=np.array([[102.631,431.897],[651.768,234.549],[431.846,790.692]])
    print(f"w1:1.9726\nw2:3.8951\nw3:2.6534")
    print(f"The price matrix is \n{arr}")
    for i in range(k):
        data = get_k_fold_data(k, i, X_train, y_train)
        net = get_net()
        train_ls, valid_ls = train(net, *data, num_epochs, learning_rate,
                                   weight_decay, batch_size)
        train_l_sum += train_ls[-1]
        valid_l_sum += valid_ls[-1]
        if i == 0:
            d2l.plot(list(range(1, num_epochs + 1)), [train_ls, valid_ls],
                     xlabel='epoch', ylabel='rmse', xlim=[1, num_epochs],
                     legend=['train', 'valid'], yscale='log')
        print(f'fold {i + 1}, train log rmse {float(train_ls[-1]):f}, '
              f'valid log rmse {float(valid_ls[-1]):f}')
    return train_l_sum / k, valid_l_sum / k # return the arv of train

In [20]:
k, num_epochs, lr, weight_decay, batch_size = 3, 200, 10, 0, 2
train_l, valid_l = k_fold(k, train_features, train_labels, num_epochs, lr,
                          weight_decay, batch_size)
print(f'{k}-折验证: 平均训练log rmse: {float(train_l):f}, '

      f'平均验证log rmse: {float(valid_l):f}')

w1:1.9726
w2:3.8951
w3:2.6534
The price matrix is 
[[102.631 431.897]
 [651.768 234.549]
 [431.846 790.692]]


RuntimeError: expected scalar type Long but found Float

In [42]:
arr=np.array([[117.320,427.985],[679.156,224.795],[423.742,781.137]])
print(f"w1:1.8962\nw2:3.7954\nw3:2.5684")
print(f"The price matrix is \n{arr}")
rate=np.array([[0.307113479,0.524065668,0.168820853],
[0.394647902,0.243632801,0.361719297],
[0.259661692,0.646278433,0.094059875],
[0.219742888,0.542690207,0.237566904],
[0.101635025,0.247316596,0.051048379],
[0.255180129,0.551132689,0.193687182],
[0.103416717,0.541657611,0.354925672],
[0.120864491,0.330785178,0.64835033],
[0.299924134,0.486169229,0.213906637],
[0.330282056,0.665050896,0.004667048]
])
price_cut=[]
for sample in rate:
    price=0
    for i in range(len(sample)):
        price+=sample[i]*(arr[i][0]-arr[i][1])
    price_cut.append(price)
price_cut=np.array(price_cut)/400
print(price_cut)

w1:1.8962
w2:3.7954
w3:2.5684
The price matrix is 
[[117.32  427.985]
 [679.156 224.795]
 [423.742 781.137]]
[ 0.20592466 -0.35295679  0.44839847  0.23351404  0.15638034  0.25478709
  0.2178287  -0.29742412  0.12817811  0.49474534]


In [87]:
import math
arr=np.array([[117.320,427.985],[679.156,224.795],[423.742,781.137]])
def type_test(rate):
    price_cut=[]
    part=[]
    for sample in rate:
        price=0
        for i in range(len(sample)):
            part.append(sample[i]*(arr[i][0]-arr[i][1]))
            price+=sample[i]*(arr[i][0]-arr[i][1])
        price_cut.append(price)
    price_cut=np.array(price_cut)/400
    '''for i in range(len(part)):
        part[i]=part[i]/(math.fabs(part[0])+
                        math.fabs(part[1])+
                        math.fabs(part[2]))'''
    total=-part[0]+part[1]-part[2]
    print(f"type_test={price_cut}")
    print(f"type:economic_forest:{part[0]/total};bio_forest:{part[1]/total};cut_forest:{part[2]/total}")
    return price_cut

a=[0.25,0.65,0.1]
W=np.array([1.9344,3.8453,2.6109])
def age_test(array):
    Z=(-math.fabs(array[0]-a[0])+(array[1]-a[1])-math.fabs(array[2]-a[2]))*10000000000000000
    print(f"age_test={Z}")
    print(f"age:little_change {array[0]-a[0]},middle_change {array[1]-a[1]},old_change {array[2]-a[2]}")
    return Z
def model(age_arr,type_arr):
    score=age_test(age_arr)+type_test(type_arr)
    print(f"The outputs is {score}")
    return score

    
    
age_arr=np.array([0.1878,0.6644+0.1191,0.0287])
type_arr=np.array([[1-0.5678-0.2319,0.5678,0.2319]])
outputs=model(age_arr,type_arr)

age_test=-0.5551115123125783
age:little_change -0.062200000000000005,middle_change 0.13349999999999995,old_change -0.0713
type_test=[0.28220019]
type:economic_forest:-0.15437209600829574;bio_forest:0.6400176616830126;cut_forest:-0.2056102423086917
The outputs is [-0.27291132]


Z=-5.551115123125783e-17


-5.551115123125783e-17

In [15]:
import random
length=10
for _ in range(10):
    t1=random.random()
    t2=random.random()
    print(t1,t2,1-t1-t2)



0.4580514407912015 0.5781232400203916 -0.03617468081159314
0.06741522005686595 0.9866539683751056 -0.054069188431971504
0.6694583219561692 0.1142208839374359 0.21632079410639493
0.6261083420245929 0.11043039750867989 0.26346126046672724
0.4633024728633858 0.815198424589936 -0.27850089745332174
0.24345486387069992 0.6993804014181245 0.05716473471117556
0.09052406216199138 0.5041282843917844 0.40534765344622425
0.5749272405428772 0.04413532262320041 0.38093743683392234
0.3497671017277644 0.8311077211087103 -0.1808748228364747
0.6918010052116884 0.3209375848780086 -0.012738590089697022


In [16]:
def init_weights(m):
    if type(m) == nn.Linear:
        nn.init.normal_(m.weight, std=0.01)


batch_size,lr,nu_epochs=2,0.1,10
loss=nn.CrossEntropyLoss()
net = nn.Sequential(nn.Flatten(), nn.Linear(784, 256), nn.ReLU(),nn.Linear(256, 10)) 
net.apply(init_weights);
trainer = torch.optim.SGD(net.parameters(), lr=lr)# net.parameters() 用于参数的保存

train_iter = d2l.load_array()
test_iter  = d2l.load_array()
d2l.train_ch3(net, train_iter, test_iter, loss, num_epochs, trainer)

TypeError: load_array() missing 2 required positional arguments: 'data_arrays' and 'batch_size'

In [73]:
import numpy as np
import math

In [74]:
b1_C_arr=np.array([[1,0.25,0.2,0.5],
[4,1,0.5,3],
[5,2,1,4],
[2,0.333,0.25,1]])
outputs=[]
# 算术
for column in b1_C_arr:
    outputs.append(column.sum())
b1_C_arr=b1_C_arr/outputs

In [19]:
b1_C_arr

array([[0.51282051, 0.02941176, 0.01666667, 0.13954786],
       [2.05128205, 0.11764706, 0.04166667, 0.83728719],
       [2.56410256, 0.23529412, 0.08333333, 1.11638292],
       [1.02564103, 0.03917647, 0.02083333, 0.27909573]])

In [34]:
# square
outputs2=[]
for column in b1_C_arr:
    demo=0
    for data in column:
        demo+=data**2
    demo=math.sqrt(demo)/4
    outputs2.append(demo)
outputs2=np.array(outputs2)
outputs2=outputs2/outputs2.sum()
outputs2

array([0.08040546, 0.33504829, 0.4239199 , 0.16062635])

In [60]:
# copied by CSDN
b2_C_arr=np.array([[1,0.25,3,9],
[4,1,6,8],
[0.333,0.167,1,3],
[0.111,0.125,0.333,1]])
RI_dict = {1: 0, 2: 0, 3: 0.58, 4: 0.90, 5: 1.12, 6: 1.24, 7: 1.32, 8: 1.41, 9: 1.45}
def get_w(array):
    row = array.shape[0]  # 计算出阶数
    a_axis_0_sum = array.sum(axis=0)
    # print(a_axis_0_sum)
    b = array / a_axis_0_sum  # 新的矩阵b
    # print(b)
    b_axis_0_sum = b.sum(axis=0)
    b_axis_1_sum = b.sum(axis=1)  # 每一行的特征向量
    # print(b_axis_1_sum)
    w = b_axis_1_sum / row  # 归一化处理(特征向量)
    nw = w * row
    AW = (w * array).sum(axis=1)
    print(f"AW:{AW}")
    max_max = sum(AW / (row * w))
    print(f"lambda_max:{max_max}")
    CI = (max_max - row) / (row - 1)
    CR = CI / RI_dict[row]
    print(f"CR:{CR}")
    if CR < 0.1:
        print(round(CR, 3))
        print('满足一致性')
        print(np.max(w))
        print(sorted(w,reverse=True))
        print(f"lambda_max{max_max}")
        print('特征向量:%s' % w)
        return w
    else:
        print(round(CR, 3))
        print('不满足一致性，请进行修改')
get_w(b2_C_arr)

AW:[1.12748482 2.62719176 0.42478659 0.182206  ]
lambda_max:4.2226847649638755
CR:0.08247583887550942
0.082
满足一致性
0.586219640350839
[0.586219640350839, 0.26617973669501965, 0.1022759061998936, 0.0453247167542478]
lambda_max4.2226847649638755
特征向量:[0.26617974 0.58621964 0.10227591 0.04532472]


array([0.26617974, 0.58621964, 0.10227591, 0.04532472])

In [44]:
import pandas as pd
filename='data.xlsx'
df=pd.read_excel(filename)
df

Index  Youth  Middle   Old       经济林       生态林        林场  Earnings/亿元·hm2
0      1   0.16    0.83  0.01  0.307113  0.524066  0.168821       168.598461
1      2   0.23    0.51  0.36  0.394648  0.243633  0.361719       147.913546
2      3   0.11    0.69  0.20  0.259662  0.646278  0.094060       174.166151
3      4   0.17    0.78  0.05  0.219743  0.542690  0.237567       166.176214
4      5   0.38    0.39  0.23  0.101635  0.847317  0.051048       163.452316
5      6   0.81    0.12  0.07  0.255180  0.551133  0.193687       171.165616
6      7   0.18    0.47  0.35  0.103417  0.541658  0.354926       149.846465
7      8   0.07    0.55  0.38  0.120864  0.830785  0.048350       169.156845
8      9   0.29    0.23  0.48  0.299924  0.486169  0.213907       141.465846
9     10   0.16    0.49  0.35  0.330282  0.665051  0.004667       154.638225

In [ ]:
rate=np.array([[0.307113479,0.524065668,0.168820853],
[0.394647902,0.243632801,0.361719297],
[0.259661692,0.646278433,0.094059875],
[0.219742888,0.542690207,0.237566904],
[0.101635025,0.247316596,0.051048379],
[0.255180129,0.551132689,0.193687182],
[0.103416717,0.541657611,0.354925672],
[0.120864491,0.330785178,0.64835033],
[0.299924134,0.486169229,0.213906637],
[0.330282056,0.665050896,0.004667048]
])